extends SceneTree
const F = preload("res://tests/unit/history/history_fixture.gd")
var failures := 0
var checks := 0
func _initialize() -> void: call_deferred("run")
func check(value: bool, message: String) -> void:
	checks += 1
	if not value: failures += 1; printerr("FAIL: "+message)
func run() -> void:
	check(ResourceLoader.exists("res://scripts/memory/memory_lifecycle.gd"),"lifecycle service exists")
	if failures: quit(1); return
	var config = load("res://scripts/memory/memory_config.gd").new()
	config.load_files()
	var ledger = load("res://scripts/history/causal_ledger.gd").new()
	ledger.append_event(F.event())
	var graph = load("res://scripts/memory/world_memory_graph.gd").new(ledger,config)
	load("res://scripts/memory/memory_encoder.gd").new(config).encode(ledger,graph,"evt_death","memory_a",[F.anchor("corpse")])
	var service = load("res://scripts/memory/memory_lifecycle.gd").new(config)
	var truth: Dictionary = ledger.serialize()
	check(service.advance(graph,1100.0),"explicit world time advances decay")
	check(graph.get_claims("memory_a")[0].retention < 1.0,"retention decays independently of confidence")
	var before: Dictionary = graph.serialize()
	check(not service.advance(graph,100.0) and graph.serialize() == before,"backward time fails atomically")
	check(service.advance(graph,1100.0) and graph.serialize() == before,"same timestamp does not decay twice")
	check(service.reinforce(graph,"memory_a","corpse","observer_a","inspection",1100.0),"inspection reinforces accessible evidence")
	var score: float = graph.get_memory("memory_a").reinforcement_score
	check(service.reinforce(graph,"memory_a","corpse","observer_a","inspection",1100.0) and graph.get_memory("memory_a").reinforcement_score == score,"same evidence cannot farm reinforcement")
	check(service.fragment(graph,"memory_a",1.0,1100.0,17),"seeded fragmentation executes")
	var visible: Array = graph.get_claims("memory_a",true)
	check(visible.size() == 1 and visible[0].semantic_residue,"details disappear while semantic residue survives")
	check(service.derive(graph,"memory_a","memory_b",F.anchor("archive","archive","archive"),1100.0,{"occurred":["unexplained_death"]},21),"distorted interpretation creates a new version")
	check(graph.get_memory("memory_b").provenance.source_memory_ids == ["memory_a"],"derived version preserves source provenance")
	check(graph.get_claims("memory_b",true)[0].object_ref_or_value == "unexplained_death","derived claim may diverge from canonical truth")
	check(graph.get_claims("memory_a",true)[0].object_ref_or_value == "character_death","source interpretation remains intact")
	check(ledger.serialize() == truth,"decay fragmentation and distortion never rewrite history")
	check(graph.query_by_event("evt_death").size() == 2,"conflicting interpretations coexist for the same event")
	var second = load("res://scripts/memory/world_memory_graph.gd").new(ledger,config)
	var encoder = load("res://scripts/memory/memory_encoder.gd").new(config)
	encoder.encode(ledger,second,"evt_death","corpse_memory",[F.anchor("body")])
	encoder.encode(ledger,second,"evt_death","relic_memory",[F.anchor("metal","world_item","relic")])
	check(service.advance(second,10100.0),"batched decay supports multiple media")
	check(second.get_claims("relic_memory")[0].retention > second.get_claims("corpse_memory")[0].retention,"metal relic retains information longer than corpse")
	var segmented = load("res://scripts/memory/world_memory_graph.gd").new(ledger,config)
	encoder.encode(ledger,segmented,"evt_death","corpse_memory",[F.anchor("body")])
	service.advance(segmented,5100.0)
	service.advance(segmented,10100.0)
	check(is_equal_approx(segmented.get_claims("corpse_memory")[0].retention,second.get_claims("corpse_memory")[0].retention),"decay does not depend on batch size")
	check(service.reinforce(graph,"memory_b","archive","observer_b","archival",1100.0),"independent archive reinforces derived interpretation")
	check(graph.get_memory("memory_b").reinforcement_score > score,"archive is stronger than inspection without validating truth")
	var deterministic = load("res://scripts/memory/world_memory_graph.gd").new(ledger,config)
	deterministic.deserialize(second.serialize())
	service.fragment(second,"corpse_memory",0.5,10100.0,42)
	service.fragment(deterministic,"corpse_memory",0.5,10100.0,42)
	check(second.serialize() == deterministic.serialize(),"same seed and state produce identical fragmentation")
	var exposed = load("res://scripts/memory/world_memory_graph.gd").new(ledger,config)
	var wet := F.anchor("wet")
	wet.environmental_exposure = 1.0
	encoder.encode(ledger,exposed,"evt_death","wet_memory",[wet])
	service.advance(exposed,10100.0)
	check(exposed.get_claims("wet_memory")[0].retention < segmented.get_claims("corpse_memory")[0].retention,"environmental exposure accelerates medium-dependent decay")
	print("MemoryLifecycle: %d checks, %d failures" % [checks,failures])
	quit(1 if failures else 0)
